name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-bdd:
    name: Build BDD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image BDD
        run: docker build ./bdd

  lint-api:
    name: Lint API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - name: Lint
        run: dotnet format ./src-api/ProjetDevOps/ProjetDevOps.csproj --verify-no-changes

  build-and-push-api:
    name: Build and Push API
    runs-on: ubuntu-latest
    needs: lint-api
    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push image API
        uses: docker/build-push-action@v6
        with:
          context: ./src-api
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{ github.repository_owner }}/api:${{ github.sha }}
          build-args: GIT_SHA=${{ github.sha }}

  integration:
    name: Docker Compose Up and Tests
    runs-on: ubuntu-latest
    needs: [build-bdd, build-and-push-api]
    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_DATABASENAME: ${{ secrets.MYSQL_DATABASENAME }}
      MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      MYSQL_USER_PASSWORD: ${{ secrets.MYSQL_USER_PASSWORD }}
      MARIADB_CONNECTIONSTRING: ${{ secrets.MARIADB_CONNECTIONSTRING }}
      GIT_REVISION: ${{ secrets.GIT_REVISION }}
    steps:
      - uses: actions/checkout@v4

      - name: Créer le .env
        run: |
          cat << EOF > .env
          MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASENAME=${MYSQL_DATABASENAME}
          MYSQL_USERNAME=${MYSQL_USERNAME}
          MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
          MARIADB_CONNECTIONSTRING=${MARIADB_CONNECTIONSTRING}
          GIT_REVISION=${GIT_REVISION}
          EOF

      - name: Docker Compose Up
        run: docker compose up -d --build

      - name: Attendre que les services soient prêts
        run: sleep 20

      - name: Test HTTP API
        run: |
          curl -f http://localhost:3120/api/weathers || \
          (docker compose logs api && exit 1)

      - name: Vérifier les services
        run: docker compose ps

      - name: Docker Compose Down
        if: always()
        run: docker compose down

  all-checks:
    name: Pipeline OK
    runs-on: ubuntu-latest
    needs: [integration]
    steps:
      - run: echo "Tous les checks sont passés"
