name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-bdd:
    name: Build BDD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image BDD
        run: docker build ./bdd

  lint-api:
    name: Lint API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - name: Lint
        run: dotnet format ./src-api/ProjetDevOps/ProjetDevOps.csproj --verify-no-changes

  build-api:
    name: Build API
    runs-on: ubuntu-latest
    needs: lint-api
    steps:
      - uses: actions/checkout@v4
      - name: Build image API
        run: |
          docker build \
            --build-arg GIT_SHA=${{ github.sha }} \
            ./src-api

  build-front:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image Frontend
        run: |
          docker build \
            --build-arg GIT_REVISION=${{ github.sha }} \
            ./src-front/weathercast

  all-checks:
    name: Pipeline OK
    runs-on: ubuntu-latest
    needs: [build-bdd, build-api, build-front]
    steps:
      - run: echo "Tous les builds sont passés"
